# Generated by Django 3.1.1 on 2020-10-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20200930_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-created'], 'verbose_name': 'Действие', 'verbose_name_plural': 'Действия'},
        ),
    ]
